spring:
  datasource:
    url: jdbc:mysql://${HOST:192.168.91.95}:3306/website
    username: ${DB_USERNAME:root}
    password: ${DB_PS:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${HOST:192.168.91.95}
      port: 6379
      password: ${PS_COMMON:password}
  rabbitmq:
    host: ${HOST:192.168.91.95}
    port: 5672
    username: ${MQ:root}
    password: ${PS_COMMON:password}
  mvc:
    log-request-details: true
  session:
    timeout: 7200

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  type-aliases-package: com.example.springdemo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    "[org.springframework.web.servlet.DispatcherServlet]": DEBUG
  file:
    name: logs/springdemo.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
      total-size-cap: 20GB
      clean-history-on-start: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
